name: CI

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.9"

    env:
      PYVER: ${{ matrix.cfg.python-version }}
      PACKAGE: teachopencadd

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          python-version: ${{ matrix.cfg.python-version }}
          environment-name: teachopencadd
          create-args: >-
            python=${{ matrix.cfg.python-version }}
          environment-file: devtools/test_env.yml
          init-shell: bash
          cache-environment: true
          cache-downloads: true
          
      - name: Activate environment
        shell: bash
        run: |
          conda activate teachopencadd

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps -vv

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Test CLI
        shell: bash -l {0}
        run: |
          teachopencadd -h
          pytest -v --cov=${PACKAGE} --cov-report=xml --color=yes ${PACKAGE}/tests/

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest $PYTEST_ARGS teachopencadd/talktorials/ $IGNORE

  format:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install format dependencies
        run: python -m pip install black-nb shyaml
      - name: Run black-nb
        run: |
          black-nb -l 99 --check teachopencadd/talktorials/T*/talktorial.ipynb

  readmes:
    name: READMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install nbformat
        run: python -m pip install nbformat shyaml
      - name: Check READMEs are up-to-date
        run: |
          for path in teachopencadd/talktorials/T*/talktorial.ipynb; do
            python devtools/regenerate_readmes.py --output README.md $path
          done
          # If the script above introduced changes (it shouldn't!), git diff will have output and an error code
          git diff --exit-code
